### PR TITLE
Provide Function Name in Code File

### PR DESCRIPTION
**Pull request by nitincodery**
How one would know the right name of the function used in test file?, I made function name just `hamming ()` and ran, it failed all test cases, then I checked test file and came to know the function name should be `hamming-distance ()`, so it should be given in code file, like it is provided in other languages.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I agree with this. I'm happy to merge this, but it would be even more awesome if you could apply this to the other exercises too. Would you be willing to do that? No worries if not.

**Comment by nitincodery** [comment]
Yes! I will apply it to all the other exercises.

**Comment by nitincodery** [comment]
I've completed adding functions to all the code files and checked them all twice and fixed all typos I did.

Handed over to review and merge team.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Great work! Thanks.

**Pull request merged**
