### PR TITLE
Fix CI tests

### PR DESCRIPTION
**Pull request by maurelio1234**
-  stub-check: set -T on tput

### CODE REVIEW

**Comment by maurelio1234** [comment]
Fixes #191 
@ErikSchierboom  what do you think?

**Review by ErikSchierboom — APPROVED** [review]
This is great! Thanks.

**Comment by maurelio1234** [comment]
@ErikSchierboom I cannot merge it.  I have not write access.

**Comment by ErikSchierboom** [comment]
Merged!

**Pull request merged**
